spring:
  application:
    name: devops-project-nikita

  datasource:
    # ???? ?????????? ???????? ????? IDEA - ????????? localhost
    # ???? ?????? Docker - ?????? ?? db-nikita (??? ??????? ?? compose)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-nikita:5432/library_db}
    username: ${SPRING_DATASOURCE_USERNAME:nikita_user}
    password: ${SPRING_DATASOURCE_PASSWORD:nikita_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Spring ??? ??????? ??????? todo_nikita
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics