- name: Copy Kubernetes manifest to the server
  copy:
    src: "{{ playbook_dir }}/../k8s/k8s_complete_Nikita.yaml"
    dest: "/home/antinikita/k8s_complete_Nikita.yaml"
- name: Apply Kubernetes manifest
  shell: "kubectl apply -f /home/antinikita/k8s_complete_Nikita.yaml --validate=false"
  ignore_errors: yes # Чтобы плейбук дошел до конца, даже если сеть барахлит