$ANSIBLE_VAULT;1.1;AES256
66313036346264613633663733343131633332316332313330646261386336616466303265636664
3162313062393832396435333630613830623832356431630a653233626364633534643230623334
30346332393131646531313134386361326162613238323438626664306565326537633233306534
3434316261623566310a383339333764306661373461666330343339373862376331623364356263
62303036373638646531373463353864343963643239366264653165363339623562616465653363
35643033636637333432323133393035373765613934646433643162393739376465303130393332
65373035306630373865613965343865313538373630663236663636663932383262393234353363
66373935656437386331306439363535616636323661303836306433643538646565393133613239
3933
